/* global describe, it, beforeEach */
'use strict'
var dateUniversal = require('../')
var assert = require('assert')
dateUniversal.UTC('UTC');
var  testDate = new Date(2016, 1, 4, 3, 24, 5, 34)
console.log(testDate.toString());
describe('date', function () {
  var date
  beforeEach(function () {
    date = new Date(2005, 6, 14, 22, 30, 41)
  })
  it('should correctly dateUniversal.date  dates', () => {
    assert.equal(dateUniversal.date('F j, Y, g:i a', date), 'July 14, 2005, 10:30 pm')
    assert.equal(dateUniversal.date('m.d.y', date), '07.14.05')
    assert.equal(dateUniversal.date('j, n, Y', date), '14, 7, 2005')
    assert.equal(dateUniversal.date('Ymd', date), '20050714')
    assert.equal(dateUniversal.date('h-i-s, j-m-y, it is w Day', date), '10-30-41, 14-07-05, 3031 3041 4 Thupm05')
    assert.equal(dateUniversal.date('D M j G:i:s Y', date), 'Thu Jul 14 22:30:41 2005')
    assert.equal(dateUniversal.date('H:i:s', date), '22:30:41')
  })

  it('should correctly dateUniversal.date dates', () => {
    assert.equal(dateUniversal.date('F j, Y, g:i a', date), 'July 14, 2005, 10:30 pm')
    assert.equal(dateUniversal.date('m.d.y', date), '07.14.05')
    assert.equal(dateUniversal.date('j, n, Y', date), '14, 7, 2005')
    assert.equal(dateUniversal.date('Ymd', date), '20050714')
    assert.equal(dateUniversal.date('h-i-s, j-m-y, it is w Day', date), '10-30-41, 14-07-05, 3031 3041 4 Thupm05')
    assert.equal(dateUniversal.date('D M j G:i:s Y', date), 'Thu Jul 14 22:30:41 2005')
    assert.equal(dateUniversal.date('H:i:s', date), '22:30:41')
  })
})

describe('date', function () {
  var testDate
  beforeEach(function () {
    testDate = new Date(2016, 1, 4, 3, 24, 5, 34)
  })
    it('should properly format date with padded zero', function () {
      assert.equal(dateUniversal.date('d', testDate), '04')
    })
    it('should properly format date without padded zero', function () {
      assert.equal(dateUniversal.date('j', testDate), '4')
    })
    it('should format date to short day name', function () {
      assert.equal(dateUniversal.date('D', testDate), 'Thu')
      testDate.setMonth(0, 31)
      assert.equal(dateUniversal.date('D', testDate), 'Sun')
      testDate.setMonth(1, 1)
      assert.equal(dateUniversal.date('D', testDate), 'Mon')
      testDate.setDate(2)
      assert.equal(dateUniversal.date('D', testDate), 'Tue')
      testDate.setDate(3)
      assert.equal(dateUniversal.date('D', testDate), 'Wed')
      testDate.setDate(5)
      assert.equal(dateUniversal.date('D', testDate), 'Fri')
      testDate.setDate(6)
      assert.equal(dateUniversal.date('D', testDate), 'Sat')
    })
    it('should format date to long day name', function () {
      assert.equal(dateUniversal.date('l', testDate), 'Thursday')
      testDate.setMonth(0, 31)
      assert.equal(dateUniversal.date('l', testDate), 'Sunday')
      testDate.setMonth(1, 1)
      assert.equal(dateUniversal.date('l', testDate), 'Monday')
      testDate.setDate(2)
      assert.equal(dateUniversal.date('l', testDate), 'Tuesday')
      testDate.setDate(3)
      assert.equal(dateUniversal.date('l', testDate), 'Wednesday')
      testDate.setDate(5)
      assert.equal(dateUniversal.date('l', testDate), 'Friday')
      testDate.setDate(6)
      assert.equal(dateUniversal.date('l', testDate), 'Saturday')
    })
    it('should format date to iso-8601 day number (monday = 1, sunday = 7)', function () {
      assert.equal(dateUniversal.date('N', testDate), '4')
      testDate.setMonth(0, 31)
      assert.equal(dateUniversal.date('N', testDate), '7')
      testDate.setMonth(1, 1)
      assert.equal(dateUniversal.date('N', testDate), '1')
      testDate.setDate(2)
      assert.equal(dateUniversal.date('N', testDate), '2')
      testDate.setDate(3)
      assert.equal(dateUniversal.date('N', testDate), '3')
      testDate.setDate(5)
      assert.equal(dateUniversal.date('N', testDate), '5')
      testDate.setDate(6)
      assert.equal(dateUniversal.date('N', testDate), '6')
    })
    it('should properly determine ordinality of the date', function () {
      assert.equal(dateUniversal.date('jS', testDate), '4th')
      testDate.setMonth(1, 1)
      assert.equal(dateUniversal.date('jS', testDate), '1st')
      testDate.setDate(2)
      assert.equal(dateUniversal.date('jS', testDate), '2nd')
      testDate.setDate(3)
      assert.equal(dateUniversal.date('jS', testDate), '3rd')
    })
 
    it('should properly format the day of the week to just a number', function () {
      assert.equal(dateUniversal.date('w', testDate), '4')
      testDate.setMonth(0, 31)
      assert.equal(dateUniversal.date('w', testDate), '0')
      testDate.setMonth(1, 6)
      assert.equal(dateUniversal.date('w', testDate), '6')
    })
    it('should return the number of days into the year', function () {
      assert.equal(dateUniversal.date('z', testDate), '34')
    })
    it('should return the long month name of the date', function () {
      testDate.setMonth(0, 31)
      assert.equal(dateUniversal.date('F', testDate), 'January')
      testDate.setMonth(1, 1)
      assert.equal(dateUniversal.date('F', testDate), 'February')
      testDate.setMonth(2, 1)
      assert.equal(dateUniversal.date('F', testDate), 'March')
      testDate.setMonth(3, 1)
      assert.equal(dateUniversal.date('F', testDate), 'April')
      testDate.setMonth(4, 1)
      assert.equal(dateUniversal.date('F', testDate), 'May')
      testDate.setMonth(5, 1)
      assert.equal(dateUniversal.date('F', testDate), 'June')
      testDate.setMonth(6, 1)
      assert.equal(dateUniversal.date('F', testDate), 'July')
      testDate.setMonth(7, 1)
      assert.equal(dateUniversal.date('F', testDate), 'August')
      testDate.setMonth(8, 1)
      assert.equal(dateUniversal.date('F', testDate), 'September')
      testDate.setMonth(9, 1)
      assert.equal(dateUniversal.date('F', testDate), 'October')
      testDate.setMonth(10, 1)
      assert.equal(dateUniversal.date('F', testDate), 'November')
      testDate.setMonth(11, 1)
      assert.equal(dateUniversal.date('F', testDate), 'December')
    })
    it('should return the month number with a padded zero (non-zero indexed)', function () {
      testDate.setMonth(0, 31)
      assert.equal(dateUniversal.date('m', testDate), '01')
      testDate.setMonth(1, 1)
      assert.equal(dateUniversal.date('m', testDate), '02')
      testDate.setMonth(2, 1)
      assert.equal(dateUniversal.date('m', testDate), '03')
      testDate.setMonth(3, 1)
      assert.equal(dateUniversal.date('m', testDate), '04')
      testDate.setMonth(4, 1)
      assert.equal(dateUniversal.date('m', testDate), '05')
      testDate.setMonth(5, 1)
      assert.equal(dateUniversal.date('m', testDate), '06')
      testDate.setMonth(6, 1)
      assert.equal(dateUniversal.date('m', testDate), '07')
      testDate.setMonth(7, 1)
      assert.equal(dateUniversal.date('m', testDate), '08')
      testDate.setMonth(8, 1)
      assert.equal(dateUniversal.date('m', testDate), '09')
      testDate.setMonth(9, 1)
      assert.equal(dateUniversal.date('m', testDate), '10')
      testDate.setMonth(10, 1)
      assert.equal(dateUniversal.date('m', testDate), '11')
      testDate.setMonth(11, 1)
      assert.equal(dateUniversal.date('m', testDate), '12')
    })
    it('should return the short month name of the date', function () {
      testDate.setMonth(0, 31)
      assert.equal(dateUniversal.date('M', testDate), 'Jan')
      testDate.setMonth(1, 1)
      assert.equal(dateUniversal.date('M', testDate), 'Feb')
      testDate.setMonth(2, 1)
      assert.equal(dateUniversal.date('M', testDate), 'Mar')
      testDate.setMonth(3, 1)
      assert.equal(dateUniversal.date('M', testDate), 'Apr')
      testDate.setMonth(4, 1)
      assert.equal(dateUniversal.date('M', testDate), 'May')
      testDate.setMonth(5, 1)
      assert.equal(dateUniversal.date('M', testDate), 'Jun')
      testDate.setMonth(6, 1)
      assert.equal(dateUniversal.date('M', testDate), 'Jul')
      testDate.setMonth(7, 1)
      assert.equal(dateUniversal.date('M', testDate), 'Aug')
      testDate.setMonth(8, 1)
      assert.equal(dateUniversal.date('M', testDate), 'Sep')
      testDate.setMonth(9, 1)
      assert.equal(dateUniversal.date('M', testDate), 'Oct')
      testDate.setMonth(10, 1)
      assert.equal(dateUniversal.date('M', testDate), 'Nov')
      testDate.setMonth(11, 1)
      assert.equal(dateUniversal.date('M', testDate), 'Dec')
    })
    it('should return the month number without a padded zero (non-zero indexed)', function () {
      testDate.setMonth(0, 31)
      assert.equal(dateUniversal.date('n', testDate), '1')
      testDate.setMonth(1, 1)
      assert.equal(dateUniversal.date('n', testDate), '2')
      testDate.setMonth(2, 1)
      assert.equal(dateUniversal.date('n', testDate), '3')
      testDate.setMonth(3, 1)
      assert.equal(dateUniversal.date('n', testDate), '4')
      testDate.setMonth(4, 1)
      assert.equal(dateUniversal.date('n', testDate), '5')
      testDate.setMonth(5, 1)
      assert.equal(dateUniversal.date('n', testDate), '6')
      testDate.setMonth(6, 1)
      assert.equal(dateUniversal.date('n', testDate), '7')
      testDate.setMonth(7, 1)
      assert.equal(dateUniversal.date('n', testDate), '8')
      testDate.setMonth(8, 1)
      assert.equal(dateUniversal.date('n', testDate), '9')
      testDate.setMonth(9, 1)
      assert.equal(dateUniversal.date('n', testDate), '10')
      testDate.setMonth(10, 1)
      assert.equal(dateUniversal.date('n', testDate), '11')
      testDate.setMonth(11, 1)
      assert.equal(dateUniversal.date('n', testDate), '12')
    })
    it('should return 0 for non-leap-years', function () {
      [2015, 2013, 2011, 2003, 1997, 1998, 1986].forEach(function (y) {
        testDate.setYear(y)
        assert.equal(dateUniversal.date('L', testDate), '0')
      })
    })
    it('should return 1 for leap-years', function () {
      [2016, 2012, 2008, 2004, 2000, 1996, 1992, 1988].forEach(function (y) {
        testDate.setYear(y)
        assert.equal(dateUniversal.date('L', testDate), '1')
      })
    })
    it('should return the number of calendar days for the set month', function () {
      assert.equal(dateUniversal.date('t', testDate), '29')
      testDate.setYear(2015)
      assert.equal(dateUniversal.date('t', testDate), '28')
      testDate.setMonth(0, 4)
      assert.equal(dateUniversal.date('t', testDate), '31')
      testDate.setMonth(3, 1)
      assert.equal(dateUniversal.date('t', testDate), '30')
    })
    it('should return the full year', function () {
      assert.equal(dateUniversal.date('Y', testDate), '2016')
      testDate.setYear(2012)
      assert.equal(dateUniversal.date('Y', testDate), '2012')
    })
  
    it('should return the truncated year (1998 -> 98)', function () {
      assert.equal(dateUniversal.date('y', testDate), '16')
      testDate.setYear(2012)
      assert.equal(dateUniversal.date('y', testDate), '12')
      testDate.setYear(2000)
      assert.equal(dateUniversal.date('y', testDate), '00')
    })
  
    it('should return am or pm depending on the hour of day', function () {
      assert.equal(dateUniversal.date('a', testDate), 'am')
      testDate.setHours(0)
      assert.equal(dateUniversal.date('a', testDate), 'am')
      testDate.setHours(23)
      assert.equal(dateUniversal.date('a', testDate), 'pm')
      testDate.setHours(12)
      assert.equal(dateUniversal.date('a', testDate), 'pm')
    })
  
    it('should return AM or PM depending on the hour of the day', function () {
      assert.equal(dateUniversal.date('A', testDate), 'AM')
      testDate.setHours(0)
      assert.equal(dateUniversal.date('A', testDate), 'AM')
      testDate.setHours(23)
      assert.equal(dateUniversal.date('A', testDate), 'PM')
      testDate.setHours(12)
      assert.equal(dateUniversal.date('A', testDate), 'PM')
    })
 
    it('should return non-military hour without a leading zero', function () {
      assert.equal(dateUniversal.date('g', testDate), '3')
      testDate.setHours(15)
      assert.equal(dateUniversal.date('g', testDate), '3')
      testDate.setHours(0)
      assert.equal(dateUniversal.date('g', testDate), '12')
      testDate.setHours(12)
      assert.equal(dateUniversal.date('g', testDate), '12')
    })
  
    it('should return military hour without a leading zero', function () {
      assert.equal(dateUniversal.date('G', testDate), '3')
      testDate.setHours(15)
      assert.equal(dateUniversal.date('G', testDate), '15')
      testDate.setHours(0)
      assert.equal(dateUniversal.date('G', testDate), '0')
      testDate.setHours(12)
      assert.equal(dateUniversal.date('G', testDate), '12')
    })
 
    it('should return non-military hour with a leading zero', function () {
      assert.equal(dateUniversal.date('h', testDate), '03')
      testDate.setHours(15)
      assert.equal(dateUniversal.date('h', testDate), '03')
      testDate.setHours(0)
      assert.equal(dateUniversal.date('h', testDate), '12')
      testDate.setHours(12)
      assert.equal(dateUniversal.date('h', testDate), '12')
    })
  
    it('should return military hour with a leading zero', function () {
      assert.equal(dateUniversal.date('H', testDate), '03')
      testDate.setHours(15)
      assert.equal(dateUniversal.date('H', testDate), '15')
      testDate.setHours(0)
      assert.equal(dateUniversal.date('H', testDate), '00')
      testDate.setHours(12)
      assert.equal(dateUniversal.date('H', testDate), '12')
    })
  
    it('should return the minutes with a leading zero', function () {
      assert.equal(dateUniversal.date('i', testDate), '24')
      testDate.setMinutes(3)
      assert.equal(dateUniversal.date('i', testDate), '03')
    })
  
    it('should return the seconds with a leading zero', function () {
      assert.equal(dateUniversal.date('s', testDate), '05')
      testDate.setSeconds(45)
      assert.equal(dateUniversal.date('s', testDate), '45')
    })
 
    it('should return the milliseconds with a leading zero', function () {
      assert.equal(dateUniversal.date('s.u', testDate), '05.034')
    })
  
})
